qTable:
  numberOfBuckets: 20
  learningRate: 0.1
  discountFactor: 0.95

environment:
  name: 'Breakout-ram-v0'
  iterations: 1000

run:
  epsilon: 0.1
  episodes: 1
  debug: true
  render: true
  renderEvery: 1
  aliveEvery: 1
