qTable:
  numberOfBuckets: 20
  learningRate: 0.1
  discountFactor: 0.95

environment:
  name: 'MountainCar-v0'
  iterations: 200

run:
  epsilon: 0.1
  episodes: 1001
  debug: true
  render: true
  renderEvery: 100
  aliveEvery: 20
