qTable:
  numberOfBuckets: 50
  learningRate: 0.1
  discountFactor: 0.95

environment:
  name: 'Breakout-ram-v0'
  renderDelay: 0.001

run:
  epsilon: 0.5
  episodes: 1001
  debug: true
  render: true
  renderEvery: 100
  aliveEvery: 20
